### ISSUE TITLE
Adding ability to view Date objects

### ISSUE THREAD

**Issue by maximgeerinck** [LanKit/DatatablesBundle#3]
How do you make it work with database objects like viewing dates, because right now it shows "[object Object]" if i try to display a date

**Comment by ChadSikorra** [comment]
Hmm...I probably don't notice this because I use the FOSRestBundle and pass the resulting DataTables search results to the view as an array and let it do the JSON encode process. Really I should encode the results to JSON with the JMSSerializerBundle within the Datatables class if it is available and add it as a suggested dependency in the composer.json file. That should convert the DateTime objects to the expected results.

**Comment by ChadSikorra** [comment]
Got around to adding this tonight. Should be resolved by commit 2d9f8c141ccfd008524f498a12d61c811259d58c . Might have to switch your composer requirement to dev-master at the moment, depending on your setup. Make sure you have the JMSSearializerBundle installed.
